services:
    mariadb:
        image: mariadb:11
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - meugerente

volumes:
    mariadb_data:

networks:
    meugerente:
        driver: bridge
