@CoreAPI_HostAddress = https://localhost:7273

POST {{CoreAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  //LoginDto
}

###

GET {{CoreAPI_HostAddress}}/api/orders

###

POST {{CoreAPI_HostAddress}}/api/orders
Content-Type: application/json

{
  //CreateOrderCommand
}

###

POST {{CoreAPI_HostAddress}}/api/orders/resetdb

###

@orderId=string
DELETE {{CoreAPI_HostAddress}}/api/orders/{{orderId}}

###

GET {{CoreAPI_HostAddress}}/api/orders/{{orderId}}

###

PUT {{CoreAPI_HostAddress}}/api/orders/{{orderId}}
Content-Type: application/json

{
  //UpdateOrderCommand
}

###
